### ISSUE TITLE
Code not working anymore, hdpiano new player

### ISSUE THREAD

**Issue by Liscum** [dcrystalj/hdpiano#1]
Hello,

First thanks for your code even if it doesn't work anymore I still managed to make it works.

I think hdpiano changed their media player by the time you did your code, they were using Vimeo before and now they use Wistia.

Line 11 you need to change : "dest = 'player.vimeo.com/video/{}?api=1&player_id=vm-player&color=f47c20&badge=0&byline=0&title=0'"
To : "dest = 'https://fast.wistia.net/embed/iframe/{}'"

I did two others little modifications.

First modification : 
For some lessons it works but for some others it cause a problem when creating the folder_name as it grep a '/' (on Linux at least). For example : 

```
>>> line = 'https://hdpiano.com/lesson/africa-by-toto/#part-4'
>>> line[27:57]
'africa-by-toto/#part-4'
```

Line 23 : "folder_name = line[27:57]"
To : "folder_name = line.split('/')[4]"

Second modification : 
If the lesson have more than 10 parts you can't download them all with your code as it only catch the last digit

Line 30 : total_videos = int(line[-1])
To : total_videos = int(line.split('-')[-1])

I'm new to GitHub, so hope doing an issue was the right way to tell you. 

Thanks.

**Comment by dcrystalj** [comment]
Can you open pull request?

lp,
Tomaz

________________________________

**Comment by dcrystalj** [comment]
fixed in https://github.com/dcrystalj/hdpiano/pull/2
