### ISSUE TITLE
Not Downloading the File

### ISSUE THREAD

**Issue by RodrigoMassa** [dcrystalj/hdpiano#5]
Hello,

Thanks for your code, dcrystalj! I am currently trying to use it and I am just starting to learn Python now so I can't really spot the source of the error I am getting. I hope to give you a good enough description of the issue (although I don't know how to solve it):

The first time I run the code, I get the following message in the console:
- Error in line 35: ValueError: invalid literal for int() with base 10: '

The folder is created with the correct name but no file is downloaded.

The second time I run it, it simply prompts the following and does not download the file:
downloading https://hdpiano.com/lesson/the-house-of-the-rising-sun-from-westworld/#part-

I have exported the cookies.txt file using the extension and the piano.txt file contains only: https://hdpiano.com/lesson/the-house-of-the-rising-sun-from-westworld/#part-4

Can you point me in the right direction of what may be causing this? If any more information is needed, let me know

Thanks again

**Comment by dcrystalj** [comment]
looks like you changed the code. line 35 is empty line. note that api might have changed already and script is not working anymore

lp,
Tomaz

________________________________

**Comment by ts23944** [comment]
Hi.. 
I got this problem after I run the download.py file..
C:\HDP>download.py
downloading https://hdpiano.com/lesson/hes-a-pirate-from-pirates-of-the-caribbean-by-klaus-badelt/#part-6
Traceback (most recent call last):
  File "C:\HDP\download.py", line 37, in <module>
    video_src = getIframeUrl(base_link+str(i), i)
  File "C:\HDP\download.py", line 14, in getIframeUrl
    bs = bs4.BeautifulSoup(r.content, 'lxml')
  File "C:\Users\Se7en\AppData\Local\Programs\Python\Python37\lib\site-packages\bs4\__init__.py", line 196, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
Please let me know what should I do to make it work? Thank you
